### ISSUE TITLE
Variable name `isvalid` confused

### ISSUE THREAD

**Issue by jacenfox** [MathGaron/pytorch_toolbox#21]
https://github.com/MathGaron/pytorch_toolbox/blob/68055faf7017b3a3e8cc96b9f87d99220f28f562/pytorch_toolbox/loop_callback_base.py#L7

Change the variable name to `istest`, `isvalidation` or `istraining` should be better.

**Comment by MathGaron** [comment]
indeed, just pick isvalidation or istraining :) (I think that istraining is better personally)

**Comment by jacenfox** [comment]
I prefer `istraining` too. In this case, we will also need to change the if statements in the callback objects. (from isvalid to istraining)

**Comment by MathGaron** [comment]
sure you can make a branch and I will merge it :)

**Comment by jacenfox** [comment]
Thanks to Mathieu.
